### PR TITLE
Binaries adhere to jshint policy

### PR DESCRIPTION
**Pull request by jhs**
Add bin/* into the `jshint` npm script, and make some minor changes to pass the test (mostly declared but unused variables).

### CODE REVIEW

**Comment by nolanlawson** [comment]
I think I know what's going on here. If you're not a contributor to the project, then it's not actually running the full test suite. I dunno. Maybe that's it.

I'm going to try to submit your change as a PR myself and see if Travis stops complaining then.

**Comment by jhs** [comment]
Okay I will push up a no-op change and see if the rebuild works now. But in the longer-term, perhaps we want outside contributors to pass Travis if they deserve it. (Maybe that's a new bug request though)

**Comment by nolanlawson** [comment]
Oh yeah definitely; it's something I've struggled with in PouchDB proper, and I still don't have a good solution for. But if we can solve it, we should. :)

**Comment by nolanlawson** [comment]
This is really bizarre. You are even a contributor now, so I have no idea why it is failing. The failure is coming from the remote server, though. It looks like it is somehow talking to CouchDB rather than Cloudant (the "missing json list of docs" error is an error that would come up if you tried to access `/_find` on CouchDB).

**Comment by nolanlawson** [comment]
OK, so based on #25, Travis seems up and running again. Not sure what was going on before. I'll rebase and then merge your PR.

**Comment by nolanlawson** [comment]
fe692205fd19730ac47bc19f822bcc1837870779 and 69163cef7b8f72852c43726ab45b3b87b3be82de

**Pull request closed without merging**
