### PR TITLE
add: worker global variable

### PR DESCRIPTION
**Pull request by zhuangya**

### CODE REVIEW

**Comment by garrensmith** [comment]
@zhuangya could you give me a bit of an more idea of what you are trying to do here?

**Comment by zhuangya** [comment]
there is no `window` in web-workers.
the global variable in web-workers is `self` instead.

the problem is: currently this plugin can not "plug it self to Pouch" automatically.

**Comment by garrensmith** [comment]
I'll have to wait on Nolan's call here. I know nothing about web workers.

**Comment by nolanlawson** [comment]
Sorry, this is not really a use case we intend to support. If you are using web workers, you are advised to explicitly call `PouchDB.plugin(...)` yourself.

Honestly the only reason we even do the `window.PouchDB` check is because we wanted to make it less complicated for developers more comfortable with `<script>` tags. If you're using web workers, then we already assume you're a power user and you can apply the plugin yourself; it's the policy I've taken with all my plugins. Thanks!

**Pull request closed without merging**
