### PR TITLE
Fields dot notation

### LINKED ISSUE #164: Field dot notation does not seem to work.
I have the following fields specified:

`"fields": ["_id", "info"]`

and receive the following as a result against a local PouchDB:

```
{
   "_id":"85-somedude-1456174210512",
   "info":{
      "zeeId":"85",
      "lastUser":"somedude",
      "lastSaved":"2016-02-23T18:12:06.389Z",
      "version":"0.1.0",
      "id":0
   }
}

```
"info" is an object with multiple properties on it and the entire object is returned. That's what I would expect.

When I try to do this, against the same PouchDB:

`"fields": ["_id", "info.lastSaved"]`

I don't get anything except "_id":

```
{
    "_id":"85-somedude-1456174210512"
}
```

### PR DESCRIPTION
**Pull request by colinskow**
Added support for nested fields using dot notation with '\\' escape in the `fields` option. Also added tests.
This resolves #164 .

### CODE REVIEW

**Comment by nolanlawson** [comment]
Seems to be failing due to lint errors, can you check your style and reformat? Thanks a lot for the PR!

**Comment by colinskow** [comment]
OK, fixed.

**Comment by nolanlawson** [comment]
Sorry, we're dealing with regressions on master due to changes in CouchDB's master branch. I'll rebase your PR so we can try to get a green run.

**Comment by nolanlawson** [comment]
See: https://github.com/nolanlawson/pouchdb-find/pull/189

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/pouchdb-find/pull/189

**Pull request closed without merging**
