### PR TITLE
Use docker for couchdb

### PR DESCRIPTION
**Pull request by garrensmith**
User docker for CouchDB 2.0 instead of manually installing it.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Looks like it's failing now because we need to pin to Node 5 instead of using Node 6.

**Comment by garrensmith** [comment]
I have another branch that I'm working on that needs to land first. That will fix the failing tests and bring it back up to par with some of the new mango changes. 

All misspelling thanks to my iPhone

**Comment by nolanlawson** [comment]
rebased

**Comment by nolanlawson** [comment]
Passing once I added `add-cors-to-couchdb`! I'm gonna go ahead and merge, because it's important to get master back to green.

**Comment by nolanlawson** [comment]
99e2c864264d1550039080d55c4390347d8564e9 and 2dba4537cf96f1cc07b56424db6189e1226b6894

**Pull request closed without merging**
