### PR TITLE
[WIP] Support query without an index

### PR DESCRIPTION
**Pull request by garrensmith**
Able to query even if there is no supported index. PouchDB-find will
fallback to using _all_docs

This is not complete yet. There are some inconsistencies in Mango that we first need to fix. I also need to get the kitchen-sink tests working.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Wait, Mango removed the thing where it would automatically fall back to the all-docs index? I thought that was a great feature. 😕 

Also can I assume this PR is still WIP? looks like a test suite is still commented out.

**Comment by garrensmith** [comment]
No the opposite. With this [commit](https://github.com/apache/couchdb-mango/commit/01252f971bef0c8da1d78bf5a7b506b71926ce1b) if it cannot find an index for the query. It uses all_docs and then does the in-memory filtering. This PR is to get pouchdb-find to do that same thing. The issue is that I came across some bugs/inconsitencies in Mango that I need fixed before I can continue here.

https://issues.apache.org/jira/browse/COUCHDB-3013
https://issues.apache.org/jira/browse/COUCHDB-3014
https://issues.apache.org/jira/browse/COUCHDB-3015

**Comment by nolanlawson** [comment]
I generated those with https://github.com/nolanlawson/pouchdb-find/blob/master/scripts/generate_kitchen_sink.py. Unfortunately it probably won't be the same the second time you generate them. You might have change them with a regex or something. :(

**Comment by nolanlawson** [comment]
merged in https://github.com/nolanlawson/pouchdb-find/pull/187

**Pull request closed without merging**
