### PR TITLE
attempt to fix couchdb master

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by nolanlawson** [comment]
`'Invalid operator: $regex'` ? OK yeah, I guess a lot has changed in Mango recently. :/

**Comment by garrensmith** [comment]
Yeah, I'm almost done. It should fix it all. 

All misspelling thanks to my iPhone

**Comment by garrensmith** [comment]
#182 should fix all these issues. I have found some bugs in mango that need to be fixed first.

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/pouchdb-find/pull/187

**Pull request closed without merging**
