### PR TITLE
Rewrite in-memory filtering

### LINKED ISSUE #118: $elemMatch on Object Arrays
Guys, first of all, cheers to your awesome work on Couch/PouchDB.

I would like to know if there is a way to query object arrays using $elemMatch, in a doc that looks something like;

```js
{ "_id": 'some_id'
  "request": 'request1',
  "events": [ {
  "eventId": 1,
  "status": 'completed' 
  }, {
  "eventId": 2,
  "status": 'pending' 
  }, {
  "eventId": 3,
  "status": 'pending' 
  }
] }
```

when I tried $elemMatch with an index on request and events I am getting all documents... Appreciate your urgent help since this is critical for completion of my current project..

### PR DESCRIPTION
**Pull request by garrensmith**
This is a rewrite of the in-memory filtering. Previously to get combinational selectors to work I had to do some very hacky code and I couldn't get `$elemMatch` to work correctly with objects as the arrays.

This is a change so that combinational and `$elemMatch` are better integrated into the way the filtering works. This will fix #118

### CODE REVIEW

**Comment by nolanlawson** [comment]
LGTM, love all the deleted code! For the jshint issue, I say we just pin the dependency to 2.8.0; this is a problem I'm running into recently in all my projects, and it stinks. :( I wish jshint had considered it a breaking change.

**Comment by nolanlawson** [comment]
:+1: when green

**Comment by psychicsaint** [comment]
Awesome.. Thanks a lot, Garren..

**Comment by dharmeshds** [comment]
Awesome.. Thanks a lot for fixing this, Garren..

**Pull request merged**
