### PR TITLE
first attempt at getting pouchdb-find working with couchdb master

### PR DESCRIPTION
**Pull request by garrensmith**
This is an initial attempt at fixing #16. My planned steps are:

- [x] Get CouchDB running on travis runs.
- [x] Fix failing tests
- [ ] Merge

### CODE REVIEW

**Comment by garrensmith** [comment]
For reference these are the current failing tests

```
 http test suite 1 http: basic should find existing indexes:
      AssertionError: expected { Object (total_rows, indexes) } to deeply equal { Object (indexes) }
      + expected - actual
             },
             "name": "_all_docs",
             "type": "special"
           }
      +  ]
      -  ],
      -  "total_rows": 1
       }
      
  
  2) http test suite 1 http: basic deletes indexes:
      AssertionError: expected { Object (total_rows, indexes) } to deeply equal { Object (indexes) }
      + expected - actual
             },
             "name": "_all_docs",
             "type": "special"
           }
      +  ]
      -  ],
      -  "total_rows": 1
       }
      
  
  3) http test suite 1 http: ddoc should create an index:
      AssertionError: expected { Object (total_rows, indexes) } to deeply equal { Object (indexes) }
      + expected - actual
             },
             "name": "foo-index",
             "type": "json"
           }
      +  ]
      -  ],
      -  "total_rows": 2
       }
      
  
  4) http test suite 1 http: ddoc should create an index, existing ddoc:
      AssertionError: expected { Object (total_rows, indexes) } to deeply equal { Object (indexes) }
      + expected - actual
             },
             "name": "foo-index",
             "type": "json"
           }
      +  ]
      -  ],
      -  "total_rows": 2
       }
      
  
  5) http test suite 1 http: ddoc should create an index, reused ddoc:
      AssertionError: expected { Object (total_rows, indexes) } to deeply equal { Object (indexes) }
      + expected - actual
             },
             "name": "foo-index",
             "type": "json"
           }
      +  ]
      -  ],
      -  "total_rows": 3
       }
      
  
  6) http test suite 1 http: eq does eq queries, no index name:
      AssertionError: expected { Object (total_rows, indexes) } to deeply equal { Object (indexes) }
      + expected - actual
               ]
             },
             "type": "json"
           }
      +  ]
      -  ],
      -  "total_rows": 2
       }
```

**Comment by nolanlawson** [comment]
Ah, I see that my tests were written before `total_rows` were introduced. That's a bugs in my tests and in pouchdb-find; I should implement it.

**Comment by garrensmith** [comment]
I'm happy to do the work but I'm on vacation next week so will only be after that. So if you have time before that then that's cool. 

All misspelling thanks to my iPhone

**Comment by garrensmith** [comment]
I've fixed all the node tests that are failing. Some issues with the tests running in the browser

**Comment by nolanlawson** [comment]
Well this is fantastic; thank you so much for your hard work! I guess it's a bit late to say I would actually have preferred to keep the Cloudant tests in there (just as a sanity check), but since this makes the dev setup a lot simpler, and since it implements total_rows, it's hard to argue with it. Nice work!

**Comment by nolanlawson** [comment]
You're now a collaborator FYI; feel free to push PRs to this repo :)

**Comment by garrensmith** [comment]
W.r.t running the tests against Cloudant. Cloudant doesn't currently support `total_rows`. Cloudant Query is slightly behind CouchDB Mango at the moment. So all the tests will fail against Cloudant at this stage. Cloudant are hoping to switch most of their code to using CouchDB 2.0 underneath. So by testing against CouchDB master we keeping the most up to date.

**Comment by srsgores** [comment]
@garrensmith, what *is* the timeline for cloudant on this switch to ``2.0`` anyways?

**Comment by garrensmith** [comment]
I'm not sure. From what I understand TBD. 

All misspelling thanks to my iPhone

**Pull request merged**
